cookietemple_version: '1.3.11 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: batchglm
project_slug_no_hyphen: batchglm
template_version: '2.0.2 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: picciama
creator_github_username: picciama
is_github_repo: true
is_repo_private: true
is_github_orga: false
full_name: Mario Picciani
email: mario.picciani@tum.de
project_name: batchglm
project_short_description: batchglm. A cookietemple based .
version: 0.1.0
license: BSD
