on: push
jobs:
  build:
    runs-on: [ubuntu-20.04, macos-latest]
    strategy:
      matrix:
        python-version: [ '3.6' ]
    name: Python ${{ matrix.python-version }} Tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python -m unittest